ln -s ../alacritty.nix alacritty.nix
ln -s ../environment.nix environment.nix
ln -s ../fzf.nix fzf.nix
ln -s ../git.nix git.nix
ln -s ../picom.nix picom.nix
ln -s ../rofi.nix rofi.nix
ln -s ../tmux.nix tmux.nix
ln -s ../vim.nix vim.nix
ln -s ../xdg.nix xdg.nix
ln -s ../xsession.nix xsession.nix
ln -s ../zsh.nix zsh.nix
