FROM zshusers/zsh

RUN apt update
RUN apt upgrade

#RUN apt install -y bat
RUN apt install -y binutils
RUN apt install -y build-essential
RUN apt install -y fd-find
RUN apt install -y fzf
RUN apt install -y git
RUN apt install -y openssh-server
RUN apt install -y neofetch
RUN apt install -y neovim
RUN apt install -y nmap
RUN apt install -y ripgrep
RUN apt install -y silversearcher-ag
RUN apt install -y net-tools

###
RUN apt install -y apt-file
RUN apt-file update


